### ISSUE TITLE
小白求教

### ISSUE THREAD

**Issue by jskjdd** [Sricor/Yiban#1]
大佬，这个具体怎么修改，要改哪些
![Uploading Snipaste_2021-09-20_19-09-47.png…]()
？

**Comment by Sricor** [comment]
手动抓一次包，修改data和extend的提交表单

**Comment by jskjdd** [comment]
这两个都改好了，运行好像出了点问题，请问这些问题怎么弄
![Snipaste_2021-09-20_23-29-20](https://user-images.githubusercontent.com/89560101/134029643-df5f7a0f-9ae6-4042-b815-a6ee3b62d637.png)
![Snipaste_2021-09-20_23-30-07](https://user-images.githubusercontent.com/89560101/134029652-2a2d3b6f-a1a0-4447-975a-e740e3ca70aa.png)

**Comment by Sricor** [comment]
每个学校都会有点不同，你可以私我下，单独写一个
