### ISSUE TITLE
疑似登录接口失效

### ISSUE THREAD

**Issue by moozae** [Sricor/yiban#20]
因为www.yiban.cn登录接口开启强制数美验证，而本库不包括验证部分，故无法正常获取access_token，至使无法正常登录。推荐已经完成过的登录的用户编写循环访问接口以使存在的cookie保活，一旦cookie过期在找到新的登录接口前将无法正常登录

**Comment by moozae** [comment]
找了个新的接口，现在可以正常登录了，代码在整理完成后会pr过来

**Comment by 265525** [comment]
登录接口已经失效，目前接口加密了。还增加了设备授权认证(但非常的鸡肋)

**Comment by moozae** [comment]
已经解决了，换了个别的接口，登录成功，代码整理完毕，稍微写一下思路就提交pr。预计半小时内

**Comment by moozae** [comment]
#21  思路写在这里了
