### ISSUE TITLE
Data和Extend需要单独调用json.dumps

### ISSUE THREAD

**Issue by kissablemt** [Sricor/yiban#5]
![image](https://user-images.githubusercontent.com/32916420/138210048-ef96ddfe-354c-429a-99d5-ed85d190e23b.png)

不知道是不是每个学校接收Str的处理方式不一样，我这边需要先把Data和Extend才能成功提交，不然就是格式错误

**Comment by Sricor** [comment]
> ![image](https://user-images.githubusercontent.com/32916420/138210048-ef96ddfe-354c-429a-99d5-ed85d190e23b.png)
> 
> 不知道是不是每个学校接收Str的处理方式不一样，我这边需要先把Data和Extend才能成功提交，不然就是格式错误

感谢，已修改。也有人反馈data和extend为字符串，这边两种方式都可行。
